### ISSUE TITLE
"undefined method" error for message.eta.minute method

### ISSUE THREAD

**Issue by sternschnuppe** [ifreecarve/nmea_plus#5]
- Calling message.ais.method always returns error:
```
 undefined method `minute' for 2016-09-22 13:30:00 +0000:Time (NoMethodError)
	from nmea_final_03.rb:43:in `block in udp_connect'
	from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.13/lib/nmea_plus.rb:103:in `block in each_complete_message'
	from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.13/lib/nmea_plus.rb:56:in `block in each_message'
	from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.13/lib/nmea_plus.rb:46:in `each_line'
	from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.13/lib/nmea_plus.rb:46:in `each_message'
	from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.13/lib/nmea_plus.rb:81:in `each_complete_message'
```
- Seen with AIVDM example messages:
```
!AIVDM,2,1,3,A,53IP:?82D2hhHUH@000<l4<Ln08uDL4TqHThhD17B;uKK6K=NOB0C@UDQh00,0*01
!AIVDM,2,2,3,A,00000000000,2*27
!AIVDM,2,1,4,A,539Hh`000000@7C;36058TlF222222222222221?88?72tkP02QiCU888888,0*70
!AIVDM,2,2,4,A,88888888880,2*20
!AIVDM,2,1,4,A,539cDeP00000@;?;K20pTD@E9<4<Q<DsR222221?8h?366LA:4TQCQ4hUDQp,0*42
!AIVDM,2,2,4,A,88888888880,2*20
!AIVDM,2,1,1,B,539G`r400000@K?K340tEHDhLtDppD000000000t306444@PJ4B0C@UDQh00,0*2E
!AIVDM,2,2,1,B,00000000000,2*26

```
-  My code
```
if message.ais.eta.nil? == false
  eta_month = message.ais.eta.month
  eta_day = message.ais.eta.day
  eta_hour = message.ais.eta.hour
  eta_minute = message.ais.eta.minute
end
```

**Comment by ifreecarve** [comment]
`message.ais.eta` returns a [ruby `time` object](https://ruby-doc.org/core-2.2.0/Time.html).  

The error message you're getting says that `minute` is not a method on that object.  A quick look at the documentation says that [the proper name of the method that returns the minutes of the date is called `min`](https://ruby-doc.org/core-2.2.0/Time.html#method-i-min).
